---
title: 'CREP_Griskevicius.Rmd'
author: "Jordan Wagge"
date: "Last Updated `r Sys.Date()`"
output: 
  html_document:
      toc: true
      toc_float: true
---

```{r packages, include=FALSE}

packages = c("tidyr", "psych", "dplyr", "ggplot2", "sjmisc")

## Now load or install&load all
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)
    }
  }
)
```
```{r setup}
url <- "https://raw.githubusercontent.com/jorowags/crep_griskevicius/main/All%20data%20without%20extension%20variables.csv"
data <- read.csv(url)
glimpse(data)
```
## Introduction

Insert introduction here

## Method

```{r}
# Descriptive statistics
# N: overall, project, country, institution, condition, race, gender
frq(data$project)
frq(data$country)
frq(data$institution)
frq(data$condition)
frq(data$race)
frq(data$gender)

# Differences between settings (online, lab, group/solo) <- original paper
# had participants completing tasks in small groups in a computer lab

# Exclusions
# Lump control conditions together? Story/no story?
# Then run Ns again
```


### Participants

### Procedures

### Materials

## Results

### Confirmatory Analyses

```{r}
# ADD GRAPHS

# From Experiment 1: 
# Original paper: 37.2% of participants chose the green
# car in the control condition, 54.5% of participants chose it in the
# status condition, chi2(1, N = 168) = 4.56, p = .033, phi = .165

# Our results:
  # Percentage selected green car by condition
 # car_table <- table(data$condition, data$greencar)
#  prop.table(car_table, 1)
  
  # Chi square test
 # chisq.test(car_table)
  
  # Phi coefficient
  # phi(car_table, digits = 3)
  
# Original paper: choice of the green cleaner increased from 25.7% in the
# control condition to 41.8% in the status condition, chisq(1, N =
# 168) = 4.52, p = .034, phi = .164

# Our results: 
  # Percentage selected green soap by condition
#  soap_table <- table(data$condition, data$greensoap)
#  prop.table(soap_table, 1)
  
  # Chi square test
 # chisq.test(soap_table)
  
  # Phi coefficient
  # phi(soap_table, digits = 3)

# Original paper: Choice of the green dishwasher
# also increased from 34.5% in the control condition to 49.1% in the
# status condition, chisq(1, N = 168) = 3.30, p = .069, eff size .140

# Our results: 
  # Percentage selected green dishwasher by condition
 # dishwasher_table <- table(data$condition, data$greendishwasher)
#  prop.table(dishwasher_table, 1)
  
  # Chi square test
#  chisq.test(dishwasher_table)
  
  # Phi coefficient
  # phi(dishwasher_table, digits = 3)

# Original paper: In
# addition to examining the influence of status motives on each
# product individually, we also analyzed the effect of status when the
# three products were combined into a composite. As predicted, a
# one-way analysis of variance (ANOVA) on the product composite
# showed a significant effect of status, F(1, 166) = 8.53, p = .004,
# d = 0.47.

# Our results: *insert code*
  # Compute composite green score
  # Count Y responses across rows
#  data$count.Y <- apply(data, 1, function(x) length(which(x=="Y")))
  
  # do ANOVA by condition
#  composite.aov <- aov(count.Y ~ condition, data = data)
 # summary(composite.aov)
  
  # effect size
 # cohen.d(data$count.Y, data$condition)
```


### Exploratory Analyses

## Discussion



```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
